### ISSUE TITLE
Long delay in the connected device

### ISSUE THREAD

**Issue by MGTRFarabler** [Macro-Deck-org/Macro-Deck#206]
Good evening, afternoon, the thing is that when you connect a device to the server, when I want to change the folder, it takes a long time to respond. I don't know what it could be but it would be great if they fixed it 

Thank you very much for your attention

**Comment by SuchByte** [comment]
This can have multiple reasons:
- Your Wi-Fi is slow
- You're using many GIFs in these folders
- You're using many icons with a high resolution on these folders

If you're using a Android device, you can try to connect over USB. You just have to do some things manually because USB is not fully implemented yet. (Make sure you're using Macro Deck 2.9.1 or higher)

1. Download adb (Android Debug Bridge)
2. Make sure you enable the USB debugging in your Android's developer options and connect it to your PC with a USB data cable
3. Open a cmd in the directory of adb.exe and type adb reverse tcp:8191 tcp:8191
4. Connect to 127.0.0.1 on the Android device

**Comment by leopardo1234** [comment]
Macro Deck 2.10.2 
when I run adb reverse tcp:8191 tcp:8191, I get this message:
C:\adb>adb reverse tcp:8191 tcp:8191
* daemon not running; starting now at tcp:5037
* daemon started successfully
And it does not connect

**Comment by joaociocca** [comment]
I dug out my old nvidia shield and thought of using this - it's battery sucks, so it's going to be always on USB cable... I was thinking it was already using that connection, it hadn't passed my mind that Macro Deck was using Wifi! Once I set the reverse adb and connected to 127.0.0.1, update delay difference was immediate! Awesome.
I don't mind setting this up to use, but is there any way to make it not dependant on ADB?
