### ISSUE TITLE
I think my windows plugin is not working good ,any help?

### ISSUE THREAD

**Issue by idobenisho** [Macro-Deck-org/Macro-Deck#285]
hello my plugin is not working , any help ?

**Comment by Xenox003** [comment]
As the template here for issues already gives you a brief intrduction in what information you need to provide, we expect you already supply the needed information for us to properly help you.

Would you please state what **exactly** your problem is. It is also useful to provide error messages or Macro Deck Logs so we can try to reproduce and properly fix your isse.
