### ISSUE TITLE
Problems with OBS 28.0.1

### ISSUE THREAD

**Issue by jesuspablo888** [Macro-Deck-org/Macro-Deck#286]
**Describe the bug**
error al conectar macro deck con OBS 28.0.1.

**Log file**
[2022-09-03.log](https://github.com/Macro-Deck-org/Macro-Deck/files/9483819/2022-09-03.log)

Please upload the latest log file (Help -> Export latest log)
![Screenshot 2022-09-03 231214](https://user-images.githubusercontent.com/48724931/188297040-ed239f0e-67f1-4694-862b-09e2fbb1f31f.png)

**Comment by Xenox003** [comment]
As OBS 28 has introduced some major changes to the websocket API, the MacroDeck OBS-Websocket plugin is no longer able to properly communicate with the OBS application.

Before OBS 28 has been released, the websocket plugin has already been changing the way it works which already made Macro Deck incompatible. Lukily the creators of the OBS Websocket plugin have been releasing a compat build for the older Websocket. As The websocket plugin got integrated into OBS 28, its no longer able to use that compat version as a fix.

For now the only way to get around this bug is by not updating to OBS 28. People are already working on a new version of the MacroDeck plugin so compatibiliy can be ensured.

**Comment by arjaymxr** [comment]
There is actually a work-around for this while using OBSv28.
https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat

**Comment by SuchByte** [comment]
The OBS plugin for Macro Deck does support V28 now.
